# Generated by Django 4.2.2 on 2023-06-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('s', 'seeds'), ('f', 'fertilizer'), ('op', 'organic_Product'), ('p', 'pesticide'), ('ft', 'farm_tools'), ('i', 'irrigation'), ('b', 'bulk'), ('af', 'animalfood')], max_length=2)),
                ('company', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='upload/products/')),
            ],
        ),
    ]
