# Generated by Django 4.2.2 on 2023-06-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangalagro', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Address',
            new_name='address',
        ),
    ]
