# Generated by Django 4.2.2 on 2023-06-24 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangalagro', '0006_payment_orderplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplace',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='orderplace',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
