# Generated by Django 4.2.2 on 2023-06-24 11:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mangalagro', '0007_alter_orderplace_ordered_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(default=datetime.datetime.today)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Packed', 'Packed')], default='Pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangalagro.customer')),
                ('payment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mangalagro.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangalagro.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='OrderPlace',
        ),
    ]
