# Generated by Django 4.2.2 on 2023-06-27 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangalagro', '0012_alter_orderplaced_status_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mangalagro.orderplaced'),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Pending', 'Pending'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
