# Generated by Django 4.2 on 2023-06-27 13:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mangalagro", "0013_complaint_order_alter_orderplaced_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="complaint", old_name="Description", new_name="description",
        ),
        migrations.RemoveField(model_name="complaint", name="customer",),
        migrations.RemoveField(model_name="complaint", name="image",),
        migrations.RemoveField(model_name="complaint", name="user",),
        migrations.AddField(
            model_name="complaint",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mangalagro.orderplaced"
            ),
        ),
        migrations.AlterField(
            model_name="orderplaced",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Packed", "Packed"),
                    ("Delivered", "Delivered"),
                    ("Accepted", "Accepted"),
                    ("On The Way", "On The Way"),
                    ("Cancel", "Cancel"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=5000)),
                ("date", models.DateTimeField(default=datetime.datetime.today)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mangalagro.orderplaced",
                    ),
                ),
            ],
        ),
    ]
