# Generated by Django 4.2.2 on 2023-06-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangalagro', '0015_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('On The Way', 'On The Way')], default='Pending', max_length=50),
        ),
    ]
