# Generated by Django 4.2.2 on 2023-08-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangalagro', '0016_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('On The Way', 'On The Way'), ('Packed', 'Packed')], default='Pending', max_length=50),
        ),
    ]
