# Generated by Django 4.2.2 on 2023-08-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangalagro', '0018_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Out of Delivery', 'Out of Delivery'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
